### ISSUE TITLE
Not uncentering in Chrome

### ISSUE THREAD

**Issue by tokc** [i-a-n/chrome-image-uncenterer#10]
There appears to be an additional `<div>` in the targeted `<body>`, which seems to cause the `img:only-child` selector to select nothing.

I was able to get the old behaviour back by removing `only-child` from the selector, but I don't know if `only-child` was there for a reason, and whether this could potentially cause problems on other pages.

**Comment by i-a-n** [comment]
interesting, thanks for the report. I'm still seeing it functioning properly in my version, 62.0 (Mac). what version are you on? and, is it possible you have another Chrome extension that's adding that extra `div`?

**Comment by tokc** [comment]
I'm on _Chrome 62.0.3202.94_ Windows 7. It's certainly possible that another extension is interfering. I'll disable other extensions and poke around a bit.

**Comment by tokc** [comment]
Indeed, I can confirm that the errant div is being added by another extension.

I suppose it wouldn't be the responsibility of one extension to work around what other extensions do, so I can't expect you to make changes based on that.

**Comment by blech** [comment]
#9 suggests it may be Better History. I'm seeing centring too and I also have that extension.
