### ISSUE TITLE
Doesn't work with all images

### ISSUE THREAD

**Issue by IndubitablyBengt** [i-a-n/chrome-image-uncenterer#2]
Works fine for hard coded urls that end in an known image extension; does not work for forum attachments e.g: [https://i.reddituploads.com/1631d08bce0a41f7aeedd8a1a6f15480?fit=max&h=1536&w=1536&s=351ef6351b9fe2c69a6c95853f05ceb2](https://i.reddituploads.com/1631d08bce0a41f7aeedd8a1a6f15480?fit=max&h=1536&w=1536&s=351ef6351b9fe2c69a6c95853f05ceb2) looks like [this](http://i.imgur.com/KUe8UzA.png).

Perhaps try to read the metadata if it is an image apply the changes then.

**Comment by i-a-n** [comment]
thanks for the note. we have an open pull request #1 that addresses this. it doesn't look quite ready for all platforms though, so I'll be working on it. thanks again!

**Comment by i-a-n** [comment]
released the updated version on [the Chrome Web Store](https://chrome.google.com/webstore/detail/chrome-image-uncenterer/olobjnglnkpmiljkdlghinhnjcdoeicl). it fixes the URL you mentioned. closing for now, thanks again!
