### ISSUE TITLE
Doesn't work with local images

### ISSUE THREAD

**Issue by IndubitablyBengt** [i-a-n/chrome-image-uncenterer#3]
If you open an image from your computer, ([example](http://i.imgur.com/aSguZmn.png)) the display is still in the new chrome style.

**Comment by i-a-n** [comment]
thanks for the report! the latest update to the extension (v0.0.2) should have fixed this bug... can you confirm that you're on the latest version and you've checked the "Allow access to file URLs" checkbox in your extensions menu, like the screenshot below?

![screenshot1486950283 1x](https://cloud.githubusercontent.com/assets/1937355/22868464/6074d54e-f164-11e6-8fdf-4413445273af.png)

**Comment by IndubitablyBengt** [comment]
Ah, that would be it! Thanks for the tip, yes that fixes it! Didn't know this was an extension option, maybe something to have a note about on the download page.
