### ISSUE TITLE
Local Files not working

### ISSUE THREAD

**Issue by elbe0011** [i-a-n/chrome-image-uncenterer#7]
macOS Sierra Version 10.12.3
Chrome Version 56.0.2924.87 (64-bit)

Local files are still being centred on a black background. Tried disabling all other extensions but the problem persists. Online images behave as expected.

Thanks for the extension!

**Comment by i-a-n** [comment]
hey, thanks for the report! sorry for the bug; my only two guesses at this time are that 1) you're on a different macOS version than I am, and I'll need to test it out on your version, or 2) perhaps you haven't checked the "Allow access to file URLs" checkbox in your Chrome extension settings:

![screenshot1486950283 1x](https://cloud.githubusercontent.com/assets/1937355/22868464/6074d54e-f164-11e6-8fdf-4413445273af.png)

can you confirm that you've checked that box, and it still doesn't work? if so, I'll try to test this out on your version of macOS. thanks!

**Comment by elbe0011** [comment]
Whoops! Completely missed that. Everything is working now. Thanks again for building this!
